"use client";

import { useState } from "react";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import {
  ShoppingCart,
  CheckCircle2,
  Clock,
  Send,
  FileText,
  DollarSign,
  Zap,
  Plus,
  Eye,
  Check,
  X,
} from "lucide-react";

interface PurchaseOrder {
  id: string;
  poNumber: string;
  supplier: string;
  status: "draft" | "pending_approval" | "approved" | "sent" | "received" | "cancelled";
  orderDate: string;
  expectedDelivery: string;
  totalAmount: number;
  itemCount: number;
  autoGenerated: boolean;
  items: Array<{
    name: string;
    quantity: number;
    unit: string;
    unitCost: number;
    total: number;
  }>;
}

const purchaseOrders: PurchaseOrder[] = [
  {
    id: "1",
    poNumber: "PO-1249",
    supplier: "Valley Fresh Farms",
    status: "pending_approval",
    orderDate: "2026-03-16",
    expectedDelivery: "2026-03-18",
    totalAmount: 1847.5,
    itemCount: 5,
    autoGenerated: true,
    items: [
      { name: "Roma Tomatoes", quantity: 200, unit: "lbs", unitCost: 2.49, total: 498 },
      { name: "Fresh Basil", quantity: 20, unit: "bunches", unitCost: 2.99, total: 59.8 },
      { name: "Avocados", quantity: 300, unit: "each", unitCost: 1.49, total: 447 },
      { name: "Lemons", quantity: 100, unit: "each", unitCost: 0.79, total: 79 },
      { name: "Mixed Greens", quantity: 50, unit: "lbs", unitCost: 5.27, total: 763.7 },
    ],
  },
  {
    id: "2",
    poNumber: "PO-1248",
    supplier: "Metro Meats",
    status: "sent",
    orderDate: "2026-03-15",
    expectedDelivery: "2026-03-17",
    totalAmount: 2496,
    itemCount: 3,
    autoGenerated: true,
    items: [
      { name: "Chicken Breast", quantity: 150, unit: "lbs", unitCost: 4.99, total: 748.5 },
      { name: "Ground Beef", quantity: 100, unit: "lbs", unitCost: 6.99, total: 699 },
      { name: "Pork Tenderloin", quantity: 80, unit: "lbs", unitCost: 7.49, total: 1048.5 },
    ],
  },
  {
    id: "3",
    poNumber: "PO-1247",
    supplier: "Pacific Seafood",
    status: "approved",
    orderDate: "2026-03-14",
    expectedDelivery: "2026-03-16",
    totalAmount: 3240,
    itemCount: 4,
    autoGenerated: false,
    items: [
      { name: "Salmon Fillet", quantity: 100, unit: "lbs", unitCost: 12.99, total: 1299 },
      { name: "Shrimp (21/25)", quantity: 80, unit: "lbs", unitCost: 11.99, total: 959.2 },
      { name: "Cod Fillet", quantity: 60, unit: "lbs", unitCost: 9.99, total: 599.4 },
      { name: "Calamari", quantity: 40, unit: "lbs", unitCost: 9.56, total: 382.4 },
    ],
  },
  {
    id: "4",
    poNumber: "PO-1246",
    supplier: "Artisan Dairy Co",
    status: "received",
    orderDate: "2026-03-12",
    expectedDelivery: "2026-03-14",
    totalAmount: 1120,
    itemCount: 3,
    autoGenerated: true,
    items: [
      { name: "Mozzarella Cheese", quantity: 50, unit: "lbs", unitCost: 6.99, total: 349.5 },
      { name: "Heavy Cream", quantity: 30, unit: "gal", unitCost: 8.99, total: 269.7 },
      { name: "Butter", quantity: 40, unit: "lbs", unitCost: 5.49, total: 500.8 },
    ],
  },
  {
    id: "5",
    poNumber: "PO-1245",
    supplier: "BulkBuy Supply",
    status: "received",
    orderDate: "2026-03-10",
    expectedDelivery: "2026-03-13",
    totalAmount: 890,
    itemCount: 6,
    autoGenerated: false,
    items: [
      { name: "All-Purpose Flour", quantity: 200, unit: "lbs", unitCost: 0.89, total: 178 },
      { name: "Sugar", quantity: 100, unit: "lbs", unitCost: 0.99, total: 99 },
      { name: "Rice", quantity: 150, unit: "lbs", unitCost: 1.29, total: 193.5 },
      { name: "Pasta", quantity: 80, unit: "lbs", unitCost: 1.49, total: 119.2 },
      { name: "Canned Tomatoes", quantity: 100, unit: "cans", unitCost: 1.99, total: 199 },
      { name: "Olive Oil", quantity: 5, unit: "gal", unitCost: 18.99, total: 101.3 },
    ],
  },
];

const monthlySpendData = [
  { month: "Oct", amount: 18500 },
  { month: "Nov", amount: 22100 },
  { month: "Dec", amount: 28400 },
  { month: "Jan", amount: 19800 },
  { month: "Feb", amount: 21300 },
  { month: "Mar", amount: 16200 },
];

function getStatusBadge(status: PurchaseOrder["status"]) {
  const config = {
    draft: { label: "Draft", variant: "secondary" as const },
    pending_approval: { label: "Pending Approval", variant: "warning" as const },
    approved: { label: "Approved", variant: "success" as const },
    sent: { label: "Sent", variant: "default" as const },
    received: { label: "Received", variant: "success" as const },
    cancelled: { label: "Cancelled", variant: "danger" as const },
  };
  const c = config[status];
  return <Badge variant={c.variant}>{c.label}</Badge>;
}

export default function OrdersPage() {
  const [selectedPO, setSelectedPO] = useState<PurchaseOrder | null>(null);

  const pendingCount = purchaseOrders.filter(
    (po) => po.status === "pending_approval"
  ).length;
  const activeCount = purchaseOrders.filter(
    (po) => po.status === "approved" || po.status === "sent"
  ).length;
  const totalPendingAmount = purchaseOrders
    .filter((po) => po.status === "pending_approval")
    .reduce((sum, po) => sum + po.totalAmount, 0);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Purchase Orders</h1>
          <p className="text-muted-foreground">
            Auto-generated and manual purchase orders
          </p>
        </div>
        <Button className="gap-2">
          <Plus className="h-4 w-4" />
          Create Order
        </Button>
      </div>

      {/* KPI Cards */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Awaiting Approval</CardTitle>
            <Clock className="h-4 w-4 text-yellow-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{pendingCount}</div>
            <p className="text-xs text-muted-foreground">
              ${totalPendingAmount.toLocaleString()} total
            </p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Active Orders</CardTitle>
            <Send className="h-4 w-4 text-blue-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">{activeCount}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">MTD Spend</CardTitle>
            <DollarSign className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">$16,200</div>
            <p className="text-xs text-green-600">-24% vs last month</p>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Auto-Generated</CardTitle>
            <Zap className="h-4 w-4 text-orange-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold">
              {purchaseOrders.filter((po) => po.autoGenerated).length}
            </div>
            <p className="text-xs text-muted-foreground">
              of {purchaseOrders.length} total orders
            </p>
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 lg:grid-cols-3">
        {/* Orders Table */}
        <Card className="lg:col-span-2">
          <CardHeader>
            <CardTitle>All Orders</CardTitle>
          </CardHeader>
          <CardContent>
            <Tabs defaultValue="all">
              <TabsList>
                <TabsTrigger value="all">All</TabsTrigger>
                <TabsTrigger value="pending">Pending</TabsTrigger>
                <TabsTrigger value="active">Active</TabsTrigger>
                <TabsTrigger value="completed">Completed</TabsTrigger>
              </TabsList>
              <TabsContent value="all" className="mt-4">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>PO #</TableHead>
                      <TableHead>Supplier</TableHead>
                      <TableHead>Items</TableHead>
                      <TableHead>Total</TableHead>
                      <TableHead>Status</TableHead>
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {purchaseOrders.map((po) => (
                      <TableRow key={po.id}>
                        <TableCell>
                          <div className="flex items-center gap-2">
                            <span className="font-medium">{po.poNumber}</span>
                            {po.autoGenerated && (
                              <Zap className="h-3 w-3 text-orange-500" title="Auto-generated" />
                            )}
                          </div>
                          <p className="text-xs text-muted-foreground">{po.orderDate}</p>
                        </TableCell>
                        <TableCell>{po.supplier}</TableCell>
                        <TableCell>{po.itemCount}</TableCell>
                        <TableCell className="font-medium">
                          ${po.totalAmount.toLocaleString()}
                        </TableCell>
                        <TableCell>{getStatusBadge(po.status)}</TableCell>
                        <TableCell>
                          <div className="flex items-center gap-1">
                            <Dialog>
                              <DialogTrigger asChild>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  onClick={() => setSelectedPO(po)}
                                >
                                  <Eye className="h-4 w-4" />
                                </Button>
                              </DialogTrigger>
                              <DialogContent className="max-w-lg">
                                <DialogHeader>
                                  <DialogTitle>
                                    {po.poNumber} - {po.supplier}
                                  </DialogTitle>
                                  <DialogDescription>
                                    {po.autoGenerated
                                      ? "Auto-generated based on demand forecast"
                                      : "Manually created order"}
                                  </DialogDescription>
                                </DialogHeader>
                                <div className="space-y-4">
                                  <div className="flex justify-between text-sm">
                                    <span>Order Date: {po.orderDate}</span>
                                    <span>Expected: {po.expectedDelivery}</span>
                                  </div>
                                  <Table>
                                    <TableHeader>
                                      <TableRow>
                                        <TableHead>Item</TableHead>
                                        <TableHead>Qty</TableHead>
                                        <TableHead>Cost</TableHead>
                                        <TableHead>Total</TableHead>
                                      </TableRow>
                                    </TableHeader>
                                    <TableBody>
                                      {po.items.map((item, i) => (
                                        <TableRow key={i}>
                                          <TableCell className="font-medium">
                                            {item.name}
                                          </TableCell>
                                          <TableCell>
                                            {item.quantity} {item.unit}
                                          </TableCell>
                                          <TableCell>${item.unitCost}</TableCell>
                                          <TableCell>${item.total.toFixed(2)}</TableCell>
                                        </TableRow>
                                      ))}
                                    </TableBody>
                                  </Table>
                                  <div className="flex justify-end text-lg font-bold">
                                    Total: ${po.totalAmount.toLocaleString()}
                                  </div>
                                </div>
                                {po.status === "pending_approval" && (
                                  <DialogFooter>
                                    <Button variant="outline" className="gap-1">
                                      <X className="h-4 w-4" />
                                      Reject
                                    </Button>
                                    <Button className="gap-1">
                                      <Check className="h-4 w-4" />
                                      Approve & Send
                                    </Button>
                                  </DialogFooter>
                                )}
                              </DialogContent>
                            </Dialog>
                          </div>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </TabsContent>
              <TabsContent value="pending" className="mt-4">
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>PO #</TableHead>
                      <TableHead>Supplier</TableHead>
                      <TableHead>Total</TableHead>
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {purchaseOrders
                      .filter((po) => po.status === "pending_approval")
                      .map((po) => (
                        <TableRow key={po.id}>
                          <TableCell className="font-medium">{po.poNumber}</TableCell>
                          <TableCell>{po.supplier}</TableCell>
                          <TableCell>${po.totalAmount.toLocaleString()}</TableCell>
                          <TableCell>
                            <div className="flex gap-1">
                              <Button size="sm" variant="outline">
                                Reject
                              </Button>
                              <Button size="sm">Approve</Button>
                            </div>
                          </TableCell>
                        </TableRow>
                      ))}
                  </TableBody>
                </Table>
              </TabsContent>
              <TabsContent value="active" className="mt-4">
                <p className="py-8 text-center text-muted-foreground">
                  {activeCount} active orders in transit
                </p>
              </TabsContent>
              <TabsContent value="completed" className="mt-4">
                <p className="py-8 text-center text-muted-foreground">
                  {purchaseOrders.filter((po) => po.status === "received").length} orders received this month
                </p>
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>

        {/* Monthly Spend Chart */}
        <Card>
          <CardHeader>
            <CardTitle>Monthly Spend</CardTitle>
            <CardDescription>Purchasing costs over time</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="h-[300px]">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={monthlySpendData}>
                  <CartesianGrid strokeDasharray="3 3" className="stroke-muted" />
                  <XAxis dataKey="month" tick={{ fill: "hsl(215, 16%, 47%)", fontSize: 12 }} />
                  <YAxis
                    tick={{ fill: "hsl(215, 16%, 47%)", fontSize: 12 }}
                    tickFormatter={(v) => `$${v / 1000}k`}
                  />
                  <Tooltip formatter={(v: number) => `$${v.toLocaleString()}`} />
                  <Bar
                    dataKey="amount"
                    fill="hsl(221, 83%, 53%)"
                    radius={[4, 4, 0, 0]}
                    name="Spend"
                  />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
